name: Postgres
description: Postgres docker container
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    POSTGRES_DB: ${{ secrets.DB_NAME }}
    POSTGRES_USER: ${{ secrets.DB_USERNAME }}
    POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
    DB_PORT: ${{ secrets.DB_PORT }}
  args:
    - ${{ env.POSTGRES_DB }}
    - ${{ env.POSTGRES_USER }}
    - ${{ env.POSTGRES_PASSWORD }}
    - ${{ env.DB_PORT }}