name: Postgres
description: Postgres docker container
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    POSTGRES_DB: ${{ secrets.db_database }}
    POSTGRES_USER: ${{ secrets.db_username }}
    POSTGRES_PASSWORD: ${{ secrets.db_password }}
    DB_PORT: ${{ secrets.db_port }}