FROM node:22-alpine

WORKDIR /usr/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000
ENV NITRO_PORT=3019

# The Nuxt specific cache-clearing and dev command
CMD ["sh", "-c", "rm -rf /tmp/nitro/worker-* && npm run dev"]