FROM node:22-slim

RUN apt-get update -y && \
    apt-get install -y wget openssl procps && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3019

# Tell Nuxt exactly which port to use AND to accept outside traffic
ENV NITRO_PORT=3019
ENV NITRO_HOST=0.0.0.0

# The Nuxt specific cache-clearing and dev command
CMD ["sh", "-c", "rm -rf /tmp/nitro/worker-* && npm run dev"]