services:
  monolith.codes-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      
  monolith.codes-backend:
    image: ghcr.io/monolith-codes/monolith-backend:latest
    restart: always
    depends_on:
      monolith.codes-postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: >
      sh -c "npx prisma migrate deploy && node dist/index.js"

  # monolith.codes-frontend:
  #   image: ghcr.io/monolith-codes/monolith-frontend:latest
  #   restart: always
  #   ports:
  #     - "3198:3000"
  #   depends_on:
  #     - monolith.codes-postgres
  #     - monolith.codes-backend
  #   environment:
  #     - NUXT_API_BASE=http://monolith.codes-backend:1909

volumes:
  pg_data: