version: "3.4"

services:
  monolith-codes-postgres:
    image: postgres:latest
    container_name: monolith-codes-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      retries: 5

  monolith-codes-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/monolith-codes-backend:latest
    container_name: monolith-codes-backend
    restart: unless-stopped
    depends_on:
      monolith-codes-postgres:
        condition: service_healthy
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@monolith-codes-postgres:${DB_PORT}/${DB_DATABASE}
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm start"