version: "3.4"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NITRO_PORT=3019
    ports:
      - 3019:3019
    command: node .output/server/index.mjs