services:
  monolith.codes-postgres:
    image: postgres:latest
    container_name: monolith-codes-postgres
    restart: always
    environment:
      POSTGRES_DB: MonoDB
      POSTGRES_USER: Monolith
      POSTGRES_PASSWORD: Mulmer123!
    ports:
      - "2109:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Monolith -d MonoDB"]
      interval: 10s
      retries: 5
  monolith.codes-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
    ports:
      - "4000:1909"
    depends_on:
      monolith.codes-postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://Monolith:Mulmer123!@monolith.codes-postgres:5432/MonoDB
    command: sh -c "npx prisma generate && npx prisma migrate deploy &&npm run dev"    # CHANGED: This forces the container to stay awake forever, 
    # even if your Node app isn't running yet.