version: "3.4"

services:
  monolith-codes-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${{ secrets.DOCKER_USERNAME }}/monolith-codes-frontend:latest
    container_name: monolith-codes
    restart: unless-stopped
    environment:
      - NITRO_PORT=3019
    ports:
      - 3019:3019
    command: node .output/server/index.mjs