FROM node:22-alpine

WORKDIR /usr/app

# Copy dependency files first to leverage Docker layer caching
COPY package*.json ./
COPY prisma ./prisma

# Install dependencies
RUN npm install

# Copy the rest of the source code
COPY . .