name: Deploy PostgreSQL Container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        id: postgres
        uses: actions/hello-world-docker-action@v2
        run: docker build -t postgres .