name: Deploy

on:
  push:
    branches:
      - main  # Setzen Sie hier den Namen Ihres Hauptzweigs ein

jobs:
  build:
    runs-on: self-hosted  # Verwenden Sie Ihren eigenen Runner
    env:
      NUXT_PORT: "3019"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: |
        cd frontend
        npm install
        npm run build

    - name: Start the application
      run: |
        cd frontend
        node .output/server/index.mjs