name: Deploy PostgreSQL Container

on:
  push:
    branches:
      - main

jobs:
  postgres_job:
    runs-on: ubuntu-latest
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_PORT: ${{ secrets.DB_PORT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker Image
        uses: ./postgres-action
        id: postgres
        env:
          POSTGRES_DB: ${{ events.DB_PASSWORD }}
          POSTGRES_USER: ${{ events.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ events.DB_DATABASE }}
          DB_PORT: ${{ events.DB_PORT }}