name: Deploy PostgreSQL Container

on:
  push:
    branches:
      - main

jobs:
  postgres_job:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        id: postgres
        uses: actions/postgres-action@v2