name: Deploy PostgreSQL Container

on:
  push:
    branches:
      - main

jobs:
  postgres_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker Image
        uses: ./postgres-action
        id: postgres
        env:
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_USERNAME: ${{ env.DB_USERNAME }}
          DB_DATABASE: ${{ env.DB_DATABASE }}
          DB_PORT: ${{ env.DB_PORT }}