name: CI/CD with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
        install: false
        use: true
      
    - name: Load environment variables from dotenv-vault
      run: |
        npm install -g dotenv-vault
        dotenv-vault -s .env.vault -t .env
        chmod 600 .env
      
    - name: Build Docker images
      run: docker-compose -f docker-compose.yml build
      
    - name: Deploy to server
      run: docker-compose -f docker-compose.yml up -d
