name: Deploy PostgreSQL Container

on:
  push:
    branches:
      - main

jobs:
  postgres_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker Image
        uses: ./postgres-action
        id: postgres
        env:
          POSTGRES_DB: ${{ secrets.DB_PASSWORD }}
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_DATABASE }}
          DB_PORT: ${{ secrets.DB_PORT }}