name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Stop and remove the running container
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.DEPLOY_SERVER }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        script: |
          cd ${{ secrets.DOCKER_PATH }}
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} docker compose down
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} docker compose pull