name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
      DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
      DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Set Docker Compose file environment variable
      run: echo "COMPOSE_FILE=docker-compose.yml" >> $GITHUB_ENV

    - name: Build Docker images using Docker Compose
      run: docker compose build

    - name: Push Docker images using Docker Compose
      run: docker compose push

  deploy:
    runs-on: ubuntu-latest
    needs: build

    env:
      COMPOSE_FILE: /home/maurice/MONOLITH/monolith.codes/docker-compose.yml

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Stop and remove the running container
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.DEPLOY_SERVER }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        script: |
          docker compose down
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} docker compose pull
          screen -xS monolith-codes-frontend
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} docker compose up -d
