name: Deploy PostgreSQL Container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run:
          using: docker
          image: postgres/Dockerfile
          args:
            - DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            - DB_USERNAME=${{ secrets.DB_USERNAME }}
            - DB_DATABASE=${{ secrets.DB_DATABASE }}
            - DB_PORT=${{ secrets.DB_PORT }}