name: PostgreSQL service example
on: [push]

jobs:
  # Label of the container job
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        export DOCKER_PW=$DOCKER_PASSWORD
        echo $DOCKER_PW |docker login -u $DOCKER_USER --password-stdin