name: Deploy PostgreSQL Container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./path/to/Dockerfile
          push: false # Set to true if you need to push the image

      - name: Deploy PostgreSQL Container
        uses: docker/metadata-action@v3
        with:
          images: username/postgres:latest # Replace with your Docker image
          args: >
            -e POSTGRES_PASSWORD=${{ env.DB_PASSWORD }}
            -e POSTGRES_USER=${{ env.DB_USERNAME }}
            -e POSTGRES_DB=${{ env.DB_DATABASE }}
            -p ${{ env.DB_PORT }}:5432
            -d postgres
