name: Deploy PostgreSQL Container

on:
  push:
    branches:
      - main

jobs:
  postgres_job:
    runs-on: ubuntu-latest
    steps:

      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_PORT: ${{ secrets.DB_PORT }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        uses: ./postgres-action
        id: postgres
        args:
        - DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        - DB_USERNAME=${{ secrets.DB_USERNAME }}
        - DB_DATABASE=${{ secrets.DB_DATABASE }}
        - DB_PORT=${{ secrets.DB_PORT }}