name: CI/CD with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
      
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver: docker-container
        buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
        install: false
        use: true
      
    - name: Build Docker images
      run: docker-compose -f docker-compose.yml build
      
    - name: Deploy to server
      run: docker-compose -f docker-compose.yml up -d
