name: PostgreSQL service example
on: [push]

jobs:
  # Label of the container job
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login@v2
    - name: Build and push PostgreSQL image
      uses: docker/build-push-action@v2
      with:
        context: postgres
        push: true
        tags: monolith_codes-postgres:latest