name: CI/CD with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
        install: false
        use: true
      
    - name: Install dotenv-vault
      run: |
        npm install dotenv
        npm install dotenv-vault
      
    - name: Fetch dotenv-vault decryption key
      run: npx dotenv-vault@latest keys ci

    - name: Build Docker images
      run: docker-compose -f docker-compose.yml --env-file .env build
      env:
        DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
      
    - name: Deploy to server
      run: docker-compose -f docker-compose.yml --env-file .env up -d
      env:
        DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
