name: CI/CD with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
        install: false
        use: true
      
    - name: Build Docker images
      run: DOTENV_KEY="${{ secrets.DOTENV_KEY }}" docker-compose build --no-cache
      
    - name: Deploy to server
      run: DOTENV_KEY="${{ secrets.DOTENV_KEY }}" docker compose -f docker-compose.yml up"
